### ISSUE TITLE
PopArt implementation?

### ISSUE THREAD

**Issue by pengzhenghao** [deepmind/scalable_agent#52]
Hi there!

I love the paper "Multi-Task Deep Reinforcement Learning with PopArt" which brings huge improvement on the base of IMPALA!

Do you have any open-sourced implementation of PopArt variant of IMPALA? Or any suggested repo for this? Thanks!

**Comment by lespeholt** [comment]
Hi, unfortunately we haven't open sourced a version of it at this point.

Best, Lasse

**Comment by steffenvan** [comment]
I open-sourced an implementation of IMPALA + PopArt a couple of years ago: https://github.com/steffenvan/IMPALA-PopArt that tries to follow the same structure as the code in this repository (with minimal changes to the structure). It's not really in a super readable state, but I think it should give an idea of how it can be done. However, since it only supports Python 2.7, I would recommend looking into this more updated version: https://github.com/aluscher/torchbeastpopart that uses Facebook's PyTorch implementation of IMPALA that integrates the PopArt normalisation with it.
